### ISSUE TITLE
Does not work on removing rogue Home Assistant Smart Apps

### ISSUE THREAD

**Issue by GTRedE** [andrewsayre/hass-smartthings-remove#4]
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/hass_smartthings_remove", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hass_smartthings_remove/remove.py", line 16, in main
    loop.run_until_complete(remove_apps(args.token))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hass_smartthings_remove/remove.py", line 25, in remove_apps
    apps = await api.apps()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 89, in apps
    resp = await self._service.get_apps(params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysmartthings/api.py", line 156, in get_apps
    return await self.get_items(API_APPS, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysmartthings/api.py", line 375, in get_items
    'get', self._api_base + resource, params, None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysmartthings/api.py", line 350, in request
    headers={"Authorization": "Bearer " + self._token}) as resp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/connector.py", line 927, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.smartthings.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')]
`

I get that error with a newly generated API token.

**Comment by GTRedE** [comment]
well, I spoke too early... I ran it from a different computer and it worked.
