### ISSUE TITLE
Can't get the app to run

### ISSUE THREAD

**Issue by sweichbr** [andrewsayre/hass-smartthings-remove#8]
Hi

I am attempting to run this but I keep getting tracebacks.  I am running HA in the Python Virtual Environment.

Here is the error:
Traceback (most recent call last):
  File "./hass_smartthings_remove", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/hass_smartthings_remove/remove.py", line 16, in main
    loop.run_until_complete(remove_apps(args.token))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/hass_smartthings_remove/remove.py", line 25, in remove_apps
    apps = await api.apps()
  File "/home/pi/.local/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 89, in apps
    resp = await self._service.get_apps(params)
  File "/home/pi/.local/lib/python3.7/site-packages/pysmartthings/api.py", line 156, in get_apps
    return await self.get_items(API_APPS, params=params)
  File "/home/pi/.local/lib/python3.7/site-packages/pysmartthings/api.py", line 375, in get_items
    'get', self._api_base + resource, params, None)
  File "/home/pi/.local/lib/python3.7/site-packages/pysmartthings/api.py", line 366, in request
    resp.raise_for_status()
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized'

**Comment by sweichbr** [comment]
Never mind, was using the old token that I had already deleted from smartthings.
